<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../nuget.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Sigourney</PackageId>
    <Description>A lightweight toolkit that helps easily writing .NET assembly weavers.</Description>
    <Copyright>$(Copyright) Contains some code from Fody, which is licensed under the MIT License as well.</Copyright>
    <PackageReleaseNotes>Fixed building projects referencing Sigourney under certain build environments like BenchmarkDotNet.</PackageReleaseNotes>
    <PackageTags>$(PackageTags);Cecil</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <!-- Due to .NET Framework's assembly loading, we are stuck to Serilog 2.x until the MSBuild sink updates.
    This applies only to MSBuild tasks on .NET Framework, where we cannot set binding redirects. Other use cases
    can freely update Serilog, but we use the latest 2.x to provide a best default option for tasks. -->
    <PackageReference Include="Serilog" Version="2.12.0" />
    <PackageReference Include="Serilog.Sinks.MSBuild" Version="1.6.0" />
  </ItemGroup>
</Project>
