<!--
Copyright (c) 2020 Theodore Tsirpanis

This software is released under the MIT License.
https://opensource.org/licenses/MIT
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
  TreatAsLocalProperty="_SigourneyEnable">
  <Import Project="$(MSBuildThisFileDirectory)Sigourney.PublishMode.targets" />
  <PropertyGroup>
    <ProcessedBySigourney>$(IntermediateOutputPath)ProcessedBySigourney</ProcessedBySigourney>
    <_SigourneyEnable Condition="$(SigourneyEnable) == false OR $(DesigntimeBuild) == true">false</_SigourneyEnable>
  </PropertyGroup>

  <!-- Legacy property supported for compatibility reasons.
  This property was introduced due to a misunderstanding of MSBuild's evaluation order, where actually the
  order we import the target files doesn't matter. Because @(SigourneyConfiguration) gets populated inside
  a target, it is guaranteed that it will be seen by the weaver targets that run afterwards. -->
  <Import
    Condition="$(_SigourneyEnable) != false AND '$(SigourneyRegisteredTargetFiles)' != ''"
    Project="$(SigourneyRegisteredTargetFiles)" />

  <Target Name="SigourneyLoadConfiguration">
    <ItemGroup>
      <SigourneyConfiguration Include="Sigourney default configuration">
        <SignAssembly>$(SignAssembly)</SignAssembly>
        <DelaySign>$(DelaySign)</DelaySign>
        <IntermediateDirectory>$(IntermediateOutputPath)</IntermediateDirectory>
        <KeyOriginatorFile>$(KeyOriginatorFile)</KeyOriginatorFile>
        <AssemblyOriginatorKeyFile>$(AssemblyOriginatorKeyFile)</AssemblyOriginatorKeyFile>
        <References>@(ReferencePath)</References>
      </SigourneyConfiguration>
    </ItemGroup>
  </Target>

  <Target
    Name="SigourneyCallWeavers"
    DependsOnTargets="SigourneyLoadConfiguration;$(SigourneyRegisteredTargets)" />

  <Target
    Name="SigourneyEntryPoint"
    Condition="$(_SigourneyEnable) != false AND '$(SigourneyRegisteredTargets)' != ''"
    AfterTargets="AfterCompile"
    Inputs="@(IntermediateAssembly)"
    Outputs="$(ProcessedBySigourney)">
    <!-- Because the dependant targets are executed before evaluating the target inputs/outputs,
    we create a separate target that depends on the weavers and imperatively call it from this
    target, after it is determined whether MSBuild should skip Sigourney or not. -->
    <CallTarget Targets="SigourneyCallWeavers" />
    <WriteLinesToFile File="$(ProcessedBySigourney)" Overwrite="true" />
    <ItemGroup>
      <!-- We can use FileWrites here because the target runs before CoreBuild. -->
      <FileWrites Include="$(ProcessedBySigourney)" />
    </ItemGroup>
  </Target>
</Project>
