<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VersionPrefix>0.4.2</VersionPrefix>
    <Authors>Theodore Tsirpanis</Authors>
    <Copyright>Copyright © Theodore Tsirpanis. Licensed under the MIT License.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/teo-tsirpanis/Sigourney</PackageProjectUrl>
    <PackageTags>ILWeaving;Sigourney</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" PrivateAssets="all" />
  </ItemGroup>
</Project>
